db:
  build: db
  container_name: mattermost-db
  restart: always
  volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  # uncomment the following to enable backup
  #environment:
  #  - AWS_ACCESS_KEY_ID=XXXX
  #  - AWS_SECRET_ACCESS_KEY=XXXX
  #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
  #  - AWS_REGION=us-east-1
app:
  build: app
  container_name: mattermost-prod
  restart: always
  links:
    - db:db
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "8065:80"
  environment:
    - VIRTUAL_HOST=chat.polycancer.org
    - LETSENCRYPT_HOST=chat.polycancer.org
    - LETSENCRYPT_EMAIL=admin@polycancer.org
